# Delete these routes and define your own shop routes here

commerce_weavers_sylius_also_bought_plugin_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: CommerceWeavers\SyliusAlsoBoughtPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

commerce_weavers_sylius_also_bought_plugin_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: CommerceWeavers\SyliusAlsoBoughtPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
