sylius_ui:
    events:
        sylius.admin.layout.topbar_right:
            blocks:
                commerce_weavers_sylius_also_bought_plugin_missing_configuration:
                    template: '@CommerceWeaversSyliusAlsoBoughtPlugin/_missing_configuration.html.twig'
                    priority: 40
